ci01:
  build: .
  ports:
   - "8080:8080"
  volumes:
   - ./jenkins:/host-config
  links:
   - mysql01
   - sonarqube01
sonarqube01:
  image: sonarqube
  ports:
  - "9000:9000"
  - "9092:9092"
  environment:
  - SONARQUBE_JDBC_USERNAME=sonar
  - SONARQUBE_JDBC_PASSWORD=sonar
  - SONARQUBE_JDBC_URL=jdbc:mysql://mysql01/sonar
  links:
  - mysql01
mysql01:
  image: mysql
  environment: 
  - MYSQL_ROOT_PASSWORD=root
